# ----------------------------------------------------------------------------------------------------------------
# RL_PtG: Power-to-Gas Dispatch Optimization using Monte Carlo Tree Search (MCTS)
# GitHub Repository: https://github.com/SimMarkt/MCTS_PtG
#
# config_mcts: 
# > Configuration file for the MTCS in the PtG-CH4 environment
# > The algorithm uses Upper Confidence Bound for Trees (UCT) to balance exploration and exploitation
# ----------------------------------------------------------------------------------------------------------------

iterations : 1000000            # No. of iterations for MCTS
exploration_weight : 1.41       # Exploration parameter for UCT
